### ISSUE TITLE
Add Scroll to Snapshot

### ISSUE THREAD

**Issue by rijulraj456** [scroll-tech/contribute-to-scroll#64] opened 2023-07-19 14:02 UTC
### Name of the project

Snapshot

### Project type

Tool

### Site of the project

https://snapshot.org/

### Github repository of the project

https://github.com/snapshot-labs/snapshot

### Networks

Scroll Mainnet

### Additional context

Suggestion to integrate with snapshot when mainnit goes live.

**Comment by uyvuqtkd** [comment] 2023-07-23 07:22
Proposal to create an administrative token distributed to the delegate group for important issues to vote on the snapshot. Of course this token can be redeemed after running the token

**Comment by isabellewei** [comment] 2023-09-08 09:58
Closing this as a duplicate of https://github.com/scroll-tech/contribute-to-scroll/issues/17

@uyvuqtkd would be great to resubmit your idea as a separate Skunkworks issue here :)

**Closed by isabellewei** 2023-09-08 09:58 UTC
Labels: integration, triage-new-issue
